### ISSUE TITLE
castep_outputs_tools library

### ISSUE THREAD

**Issue by oerc0122** [oerc0122/castep_outputs_tools#1]
Add a separate library of tools using castep_outputs to analyse outputs. May also provide hooks for other software.

- [ ] oerc0122/castep_outputs#136 
- [ ] oerc0122/castep_outputs#117 
- [ ] oerc0122/castep_outputs#167
- [ ] oerc0122/castep_outputs#168
